blocks:
  #  ca start
  ca: "MutilHeadCrossAttentionBlock"
#  ca: "MutilHeadSelfAttentionBlock"
  #  ca end

  #  cls start
  cls_head: "GeMClassifier"
#  cls_head: "LiteTransformerPoolCls"
#  cls_head: "MixPoolClassifier"
#  cls_head: "PatchTransformerPoolCls"
#  cls_head: "SAOLPoolCls"
#  cls_head: "SPPoolCls"
#  cls_head: "TransformerPoolCls"
  #  cls end

  #  DIFB start
  DIFB: "DIFB2D"
#  DIFB: "DIFB2D_v1"
  #  DIFB end

  #  feature_fusion start
  feature_fusion: "AFFFeatureFsuion"
#  feature_fusion: "ConvFeatureFsuion"
  # feature_fusion end

  #  upsample start
  upsample: "PatchExpandConvTranspose"
#  upsample: "PatchExpandPixelShuffle"
#  upsample: "PatchExpandUpsample"
  #  upsample end